#!/usr/bin/perl
#
# Scanner for software RAID arrays
#
# Author:  Madison Kelly, mkelly@alteeve.ca
# Version: 0.1

use strict;
use warnings;

# Add the 'scan.d' directory to perl's @INC array so that the libraries can be
# found.
my $inc_directory = $ENV{PWD}."/scan.d";
push @INC, $inc_directory;
require "scan-common-perl.lib";
require "storage_mdadm.lib";

# Before anything, tell the caller that this is a Striker agent.
print "Striker Agent: storage_mdadm\n";

my $conf = initialize();
get_switches($conf);

# Tell the scanner about us.
report_xml($conf);


exit(0);


# Initialize.
sub initialize
{
	my $conf = {
		path	=>	{
			mdadm	=>	"mdadm",
			mdstat	=>	"/proc/mdstat",
		},
	};
	
	# Find the paths of executables that are not fully defined.
	find_executables($conf);
}

exit(0);
