#!/usr/bin/perl
#
# AN!Striker - Alteeve's Niche! Dashboard for "Anvil" VM clusters
# 
# This software is released under the GNU GPL v2+ license.
# 
# No warranty is provided. Do not use this software unless you are willing and
# able to take full liability for it's use. The authors take care to prevent
# unexpected side effects when using this program. However, no software is
# perfect and bugs may exist which could lead to hangs or crashes in the
# program, in your cluster and possibly even data loss.
# 
# If you are concerned about these risks, please stick to command line tools.
# 
# This program is designed to extend clusters built according to this tutorial:
# - https://alteeve.com/w/2-Node_Red_Hat_KVM_Cluster_Tutorial
#
# This program's source code and updates are available on Github:
# - https://github.com/digimer/an-cdb
#
# Author;
# Alteeve's Niche!  -  https://alteeve.com
# Madison Kelly     -  mkelly@alteeve.ca
# 
# TODO:
# - Read and cache each cluster's /etc/hosts file.
# - Check to see if a VM is running outside of clustat and, if so, auto-enable
#   it on the appropriate node.
# - Add a "Cancel" button to each "Confirm" box.
# - Add an ability to trigger a status email. SIGUSR1 via script -> email
# - Allow users to rename VMs.
# - Add 'virsh undefine' when deleting VMs if 'virsh list --all' shows it still
#   defined on one of the VMs.
# - Build a VM outside of the cluster and sort out a way to have the dashboard
#   insert it into the cluster.
# - Make "Node -> Offline" be a "Warning!"
# - Make "Bond -> Down" be a warning

use strict;
use warnings;
use IO::Handle;
require 'common.lib';

my $THIS_FILE = "striker";
print "Content-type: text/html; charset=utf-8\n\n";
print "Hello, world.\n";

exit (0);
